version: "3.9"

services:
  # hihear_be:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: hihear-backend
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     DB_TYPE: postgres
  #     DB_HOST: hihear-database
  #     DB_PORT: 5432
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: postgres
  #     DB_DATABASE: hihear
  #   restart: always
  #   volumes:
  #     - ./backend:/app  
  #     - /app/node_modules 
  #   depends_on:
  #     - hihear-database

  hihear-database:
    image: postgres:16
    container_name: hihear-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hihear
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - hihear-database
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
volumes:
  pg_data:
